# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kubernetes-poc
  namespace: kubernetes-poc-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-poc
  template:
    metadata:
      namespace: kubernetes-poc-staging
      labels:
        app: kubernetes-poc
    spec:
      containers:
      - name: kubernetes-poc
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/poc-kubernetes-node/nest:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"